spring.application.name=series_db
spring.datasource.url=jdbc:mysql://localhost:3306/series_db
spring.datasource.username=root
spring.datasource.password=Mateusmateus#1

// Instrui o JPA a criar a tabela automaticamente na primeira vez
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true